from typing import List, Optional

from openai import OpenAI

from llm_models.class_llm import LLM


class Openia_LLM(LLM):
    def __init__(self):
        self.API_KEY = "YOUR-API-KEY"
        self.MODEL_MINI = "gpt-4.1-mini"
        self.MODEL_STANDARD = "gpt-4.1"
        self.MODEL_REASONING_MINI = "gpt-4o-mini"
        # self.API_KEY = "sk-b097087195764609aa93a5ceb58cbd9f"
        # self.MODEL_NAME = "deepseek-chat"
        self.client = OpenAI(api_key=self.API_KEY)

    def generate_output_schema(self, problem: str) -> str:
        system_prompt = """
Define a unified output structure (e.g., object or dictionary) that standardizes the result format for the given problem.
- Use Python-compatible syntax.
- Define only the structure.
- Use English for all variable names.
- Include inline comments explaining the purpose of each variable.
- Do NOT provide examples.
- Do NOT include any extra text or comments.
"""

        try:
            response = self.client.chat.completions.create(
                model=self.MODEL_MINI,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": problem},
                ],
                stream=False,
                response_format={"type": "text"},
                temperature=0.0,
            )

            content = response.choices[0].message.content
            if content is None:
                raise Exception("No content found in the response.")

            return content
        except Exception as e:
            print(f"Error generating output schema: {e}")
            raise e

    def generate_prompt_restrictions(self, problem: str) -> str:
        system_prompt = """
Generate a list of all constraints described in the problem.
- The list must be ordered by priority.
- Each constraint must be a separate text string.
- Each constraint must appear on its own line.
- Each constraint must follow a consistent format.
- Write the list in English only.
"""

        user_prompt = f"""
-------------PROBLEM-------------
{problem}
"""
        try:
            response = self.client.chat.completions.create(
                model=self.MODEL_REASONING_MINI,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                stream=False,
                response_format={"type": "text"},
                temperature=1.0,
            )

            content = response.choices[0].message.content
            if content is None:
                raise Exception("No content found in the response.")

            return content
        except Exception as e:
            print(f"Error generating prompt restrictions: {e}")
            raise e

    def generate_code_restrictions(self, problem: str, prompt: str, input_schema: str) -> str:
        system_prompt = """
Generate a complete, executable Python function named validate_restrictions that checks all constraints described in the problem.
- The function must accept a parameter named result, which follows the input_schema format.
- It must return a Tuple[bool, str], indicating whether the result satisfies all constraints; if not, the string must explain the reason in English.
- The function must ensure that all values in result are derived from the input instance and do not introduce arbitrary data.
- If necessary to validate any restriction, the function must load the instance data required for validation.
- Include all necessary imports and instance data loading within the function.
- All text must follow UTF-8 encoding.
- Only output the function code. Do NOT execute it or add extra text.
- The function is: def validate_restrictions(result: Dict) -> Tuple[bool, str]:
"""
        user_prompt = f"""
-------------PROBLEM-------------
{problem}
-------------PROMPT-------------
{prompt}
-------------INPUT SCHEMA-------------
{input_schema}
"""

        try:
            response = self.client.chat.completions.create(
                model=self.MODEL_STANDARD,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                stream=False,
                response_format={"type": "text"},
                temperature=0.0,
            )

            content = response.choices[0].message.content
            if content is None:
                raise Exception("No content found in the response.")

            return content
        except Exception as e:
            print(f"Error generating validate restrictions: {e}")
            raise e

    def generate_code_target_function(self, problem: str, input_schema: str) -> str:
        system_prompt = """
Write a complete and executable Python 3 function named target_function that evaluates the quality of a result object generated by a proposed solution.
- The function must accept a parameter result, which follows the input_schema.
- It must return a numeric score (int or float) reflecting how well the result meets the problem's objectives.
- The score must be between 0 and 100, where 100 is the best possible score.
- Clearly define the evaluation criteria (e.g., accuracy, efficiency, coverage, penalties).
- Ensure the code is UTF-8 encoded and Python 3 compatible.
- In case of invalid input or error, the function must either return a score of 0 or raise an exception with an English error message.
- Output only the function code, without extra text.
"""

        user_prompt = f"""
-------------PROBLEM-------------
{problem}
-------------INPUT SCHEMA-------------
{input_schema}
"""
        try:
            response = self.client.chat.completions.create(
                model=self.MODEL_STANDARD,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                stream=False,
                response_format={"type": "text"},
                temperature=0.0,
            )

            content = response.choices[0].message.content
            if content is None:
                raise Exception("No content found in the response.")

            return content
        except Exception as e:
            print(f"Error generating prompt restrictions: {e}")
            raise e

    def generate_first_problems_prompts(self, problem: str, output_schema: str, num_prompts: int) -> List[str]:
        system_prompt = f"""
Generate {num_prompts} distinct prompts for solving the stated problem using code.
- Each prompt must specify that the code must be written in Python.
- The code must return only the result when executed, with no additional output.
- Each prompt must use a different approach (e.g., heuristics, metaheuristics, exact algorithms, etc.).
- The use of external solvers (e.g., OR-Tools, PuLP, or similar optimization libraries) is strictly prohibited.
- Each prompt must be independent of the others.
- Each prompt must include step-by-step instructions to solve the problem.
- Each prompt must include the required output schema in the prompt body, using the following format: {output_schema}
- Do NOT include examples, extra text, or comments.
- All prompts must be written in English.
- Separate each prompt with a line of 25 hash symbols (#########################).
- Return only the {num_prompts} prompts.
"""

        try:
            response = self.client.chat.completions.create(
                model=self.MODEL_REASONING_MINI,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": problem},
                ],
                stream=False,
                response_format={"type": "text"},
                temperature=1.0,
            )

            content = response.choices[0].message.content
            if content is None:
                raise Exception("No content found in the response.")

            prompts = []
            for prompt in content.split(25 * "#"):
                cleaned_prompt = prompt.strip()
                if cleaned_prompt:
                    prompts.append(cleaned_prompt)

            return prompts
        except Exception as e:
            print(f"Error generating problems prompts: {e}")
            raise e

    def generate_code(self, problem: str, prompt: str, output_schema: str, inspiration: Optional[str] = None) -> str:
        system_prompt = """
You are a Python developer. Write complete, executable Python code to solve the stated problem.
- The code must follow the specified output_schema format.
- When executed, the code must return and print only the result to the console.
- Do not print any additional information.
- Do not generate your own data or example instances; the problem statement already supplies them.
"""
        user_prompt = f"""
-------------PROBLEM-------------
{problem}
-------------INSPIRATION-------------
{inspiration}
-------------PROMPT-------------
{prompt}
-------------OUTPUT SCHEMA-------------
{output_schema}
"""

        try:
            response = self.client.chat.completions.create(
                model=self.MODEL_STANDARD,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                stream=False,
                response_format={"type": "text"},
                temperature=0.0,
            )

            content = response.choices[0].message.content
            if content is None:
                raise Exception("No content found in the response.")

            return content
        except Exception as e:
            print(f"Error generating code: {e}")
            raise e

    def generate_prompt_evolution(self, problem: str, code: str) -> str:
        system_prompt = """
Generate a comprehensive list of all possible improvements to achieve the objective function and enhance execution speed for the given code that is not reaching the expected objective function for the problem.
- The list must be ordered by priority (highest impact first)
- Each improvement must be a separate text string
- Each improvement must appear on its own line
- Each improvement must follow a consistent format: [Category]: Description - Expected impact
- Categorize improvements into: Algorithm, Data Structure, Performance, Logic, Implementation, Architecture
- Provide specific, actionable recommendations
- Write the list in English only
- Focus on measurable improvements that directly impact the objective function

Critical Instructions for Implementation Safety:
- Provide implementation-safe recommendations that minimize coding errors
- Include specific precautions and validation steps for each improvement
- Mention potential pitfalls and how to avoid them
- Reference exact function/method names and parameters when applicable
- Include data type specifications and boundary conditions
- Specify order of implementation to avoid dependency issues

Enhanced Format Requirements:
Each improvement must include:
- Clear description of what needs to be changed
- Specific implementation steps in logical order
- Validation method to verify the change works
- Potential risks and how to mitigate them
- Dependencies that must be addressed first
"""

        user_prompt = f"""
-------------PROBLEM-------------
{problem}
-------------CODE-------------
{code}
"""
        try:
            response = self.client.chat.completions.create(
                model=self.MODEL_REASONING_MINI,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                stream=False,
                response_format={"type": "text"},
                temperature=1.0,
            )

            content = response.choices[0].message.content
            if content is None:
                raise Exception("No content found in the response.")

            return content
        except Exception as e:
            print(f"Error generating prompt restrictions: {e}")
            raise e

    def generate_evolution_code(self, problem: str, output_schema: str, code: str, list_improvements: str) -> str:
        system_prompt = """
You are a Python developer. Your task is to improve, optimize, and evolve the provided Python code to better solve the stated problem.
- The final code must be complete, executable, and written in Python.
- It must strictly follow the specified output_schema format.
- When executed, the code must return and print only the result to the console.
- Do not print any additional information.
- Focus on enhancing performance, readability, and compliance with best practices.
"""
        user_prompt = f"""
-------------PROBLEM-------------
{problem}
-------------CODE TO EVOLVE-------------
{code}
-------------OUTPUT SCHEMA-------------
{output_schema}
-------------LIST OF IMPROVEMENTS-------------
{list_improvements}
"""

        try:
            response = self.client.chat.completions.create(
                model=self.MODEL_STANDARD,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                stream=False,
                response_format={"type": "text"},
                temperature=0,
            )

            content = response.choices[0].message.content
            if content is None:
                raise Exception("No content found in the response.")

            return content
        except Exception as e:
            print(f"Error generating code: {e}")
