agents:
  coding-model:
    provider: OPENAI
    config:
      api-key: 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
      model: gpt-4.1
      
  planning-model:
    provider: OPENAI
    config:
      api-key: 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
      model: gpt-4o-mini

problem:
  context: |
    En este problema de empaquetado unidimensional, una empresa de envíos busca optimizar la forma en que distribuye una cantidad de productos en cajas, con el objetivo de minimizar el número total de cajas necesarias. 
    Cada producto tiene un tamaño definido, y todas las cajas poseen una capacidad máxima uniforme. 
    Se asume que la cantidad de cajas disponibles es infinita, por lo que el problema consiste en determinar cuántas cajas son necesarias y cómo asignar los productos a ellas de manera que ninguna caja exceda su capacidad.

  objective: |
    Minimizar la cantidad total de cajas necesarias para empaquetar todos los productos.

  constraints: |
    - Cada producto debe ser asignado exactamente a una caja.

    - La suma de los tamaños de los productos en una caja no puede exceder su capacidad.

    - Cada caja debe contener al menos un producto.
  
  instance-filename: "instance.txt"
  instance-format: |
    Para una instancia de 200 productos con paquetes de tamaño 100, tenemos la siquiente estructura:

    Primera parte de la representación
      100 200
    - El primer valor indica el tamaño de cada paquete, y el segundo indica el número total de paquetes. Luego, tenemos:

    Segunda parte de la representación
      42
      69
      67
      57
      93
      90
      38
      36
      45
      42
      ... 190
    - La segunda parte del archivo muestra el tamaño de cada paquete, en este caso, 200 valores

generation:
  first-generation-size: 10
  max-epochs: 5
  evolution-strategy: "individual" # "individual" | "cross"
  selection-strategy: "best" # "best" | "random"
  timeout: 30 # seconds
  max-errors: 5 # max number of errors resolved in a single generation